### ISSUE TITLE
add release changelog in release-app and in the app ui

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#169]
definition of done:
- when user updated app (e.g. app got restarted) it shows a dialog with changelog
- at the end of release-app.yml something read all commits since last app release and put it openai prompt and ask "generate a summary ...." (figure out a prompt that would give useful and concise changelog bullet list to user) and then it would update a CHANGELOG.md, the app dialog could just embed this file in the dialog, simple 

tips:
- i can give you an openai key, dm me on discord, x, telegram @louis030195 
- create a script if you need to in .github/scripts dir 
- you can use https://github.com/nektos/act to test github action (but likely dont need, just run the script right?)

/bounty 100

**Comment by ologbonowiwi** [comment]
I want to attempt this. 

My implementation plan:
- create a changelog folder
- generate a changelog with `<version>.md` on release
- show the latest changelog/the changelog matching the current version upon restarting 

Thoughts @louis030195?

**Comment by louis030195** [comment]
> I want to attempt this.
> 
> My implementation plan:
> 
> * create a changelog folder
> * generate a changelog with `<version>.md` on release
> * show the latest changelog/the changelog matching the current version upon restarting
> 
> Thoughts @louis030195?

sounds good

can you put in the content/changelog folder? dont like when there are too many files at the root 

also "show the latest changelog/the changelog matching the current version upon restarting" preferably should not show twice the same changelog to user (say i update app, restart, see dialog, then close restart app, it should not show again, you can just store something in localstorage probably to avoid this)

**Comment by ologbonowiwi** [comment]
Do you have any video or step-by-step on what happens when a user updates the app?

I saw only now this 
> then it would update a CHANGELOG.md, the app dialog could just embed this file in the dialog, simple

It's way simpler than I had in mind. What I'm thinking now is that we can have a flag on `localStorage`, for example, saying `showChangelog`, which will be set to `false` once the user closes the changelog dialog. When the app restarts/updates, we set this to `true`, and on first initiation, the app will check it and show the dialog if the flag is set to true.

Alternatively, if we have any variable on-app holding the current version of the system, we can have a variable on `localStorage`, something like `lastUsedVersion`. At each initiation, we compare the value from `lastUsedVersion` with the variable from the app that holds the _actual_ current version. If they differ, we then show the dialog. 

Additionally, I was wondering if we should show a changelog for the user-built app. If so, somehow, we need to keep track of the version the user is using (in this case, maybe we can use commit?). If this isn't important, we can ignore it and say it's only available on the paid version. Let me know what you think.

**Comment by louis030195** [comment]
@ologbonowiwi any news on this?

**Comment by ologbonowiwi** [comment]
I generated the changelog, but I don't think I’ll have the bandwidth to handle everything. 

Should I open a PR with the changelog generation? Prob you can cut off this from the issue, and whoever finishes will only need to do the app notification part

**Comment by AmanNegi** [comment]
I'd be willing to implement it on the dialog/app side.

**Comment by ologbonowiwi** [comment]
would you agree on getting half of the bounty for the dialog/app side? I did the other side which is open ai prompt/integration and changelog generation at release.

@louis030195 mind you review #544? we could get it merged so @AmanNegi will have the files to work on the dialog part of it.

**Comment by AmanNegi** [comment]
Sure sounds good to me @ologbonowiwi. I'll begin by implementing the dialog behavior as requested.

**Comment by ologbonowiwi** [comment]
what about reviewing/merging my work from #544? I'm fine getting the bounty as a tip or with a /split later, in case there's anything that needs to be done on my side
