### ISSUE TITLE
make CLI available in PATH

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#421]
when installing app it should put CLI in PATH (on all OSes)

**Comment by divanshu-go** [comment]
@louis030195 Is this open ?
BTW when should we do this ?
are you talking about the desktop app that users build themselves using bun.

**Comment by louis030195** [comment]
the goal is to make people be able to do 

`screenpipe`

from anywhere on their computer, the CLI is packaged in the app

instead of having to call the absolute path 

so i guess it should edit global PATH of windows and IDK on macos/linux, maybe symlink or idk in /usr/local/bin, ask AI

**Comment by divanshu-go** [comment]
@louis030195 OK
we can show manual instructions because sometimes users do not want it set automatically
### Adding screenpipe to PATH:

Windows:
1. Open "Environment Variables" (Win + R, type "sysdm.cpl")
2. Edit "Path" under User Variables
3. Add the folder containing screenpipe.exe

macOS/Linux:
1. Add to ~/.zshrc or ~/.bashrc:
   export PATH="/path/to/screenpipe/folder:$PATH"
2. Reload with: source ~/.zshrc

Verify installation:
$ screenpipe --version

Note: Replace "/path/to/screenpipe/folder" with the actual folder path
containing the screenpipe binary.

**Comment by louis030195** [comment]
i think you did not understand the task

it should be automated

**Comment by divanshu-go** [comment]
Yes we can automate it accordingly 
On every execution of `screenpipe setup` and `screenpipe` , we can get the current path of binary and set it in the PATH
