### ISSUE TITLE
option to only capture the window currently focused (e.g. the window where there is a mouse in)?

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#465]
would it make sense to have an option (that could be true by default) to only capture the window currently focused (e.g. the window where there is a mouse in)?

**Comment by bhupesh-sf** [comment]
@louis030195 This is I think most of the users believe they want by default. Some use case can be there where people may want to capture something going on in another window in background. So we should be giving option to select additional windows along with default current window. Now regarding mouse I am not sure. Because while coding I have 2 screens, generally active screen is the one where I am typing my code and cursor is on the screen. Not sure how to do it.

**Comment by louis030195** [comment]
basically some users want:
- only record a specific window or app
- others want only focused window

so we need to leave customisable for each


i don't even know what we record exactly right now actually, would be good to investigate this, if it's all windows including background one, etc
