### ISSUE TITLE
[bounty] self hosted runner on cloud

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#566]
github action runner are trash and i got charged $50 for a single run of their bigger runner

we want to use cloud, like GCP kubernetes or something like this to speed up things and stop crashing because out of storage

need more precision but should be a one liner for us like a script that create a cluster and setup things for github ideally 

bounty TBD

**Comment by Neptune650** [comment]
> github action runner are trash and i got charged $50 for a single run of their bigger runner
> 
> we want to use cloud, like GCP kubernetes or something like this to speed up things and stop crashing because out of storage
> 
> need more precision but should be a one liner for us like a script that create a cluster and setup things for github ideally
> 
> bounty TBD

Well this can't be done with a single one liner because the process varies between OSes...
So what exactly do you wish to do

Generally though, it boils down to:
- Creating a server in whatever cloud service, logging into it through SSH. (can be done through an API)
- Install the GitHub [runner](https://github.com/actions/runner/releases) application via SSH
- Get a config token through the GitHub UI or use the GitHub API POST endpoint which is `/repos/{owner}/{repo}/actions/runners/registration-token`

**Comment by Neptune650** [comment]
@louis030195 Could you please check this

**Comment by louis030195** [comment]
@Neptune650 i want to speed up windows build which takes 60m atm so let's prioritize this 

i have $5k azure credit (prob more) so let's use this 

can i invite you to the azure thing and let you handle this?

just DM me email and the github token you need

**Comment by Neptune650** [comment]
> @Neptune650 i want to speed up windows build which takes 60m atm so let's prioritize this 
> 
> i have $5k azure credit (prob more) so let's use this 
> 
> can i invite you to the azure thing and let you handle this?
> 
> just DM me email and the github token you need

@louis030195 Hello, we could also talk this through Telegram, I've sent you a message.

**Comment by louis030195** [comment]
/tip $150 @Neptune650 

awesome work
