### ISSUE TITLE
[feature] $150 save which window is focused 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#683]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/680faae9-3e88-4ec1-8a4a-7f5e19188e5b">

- save in db a boolean active or not 
- use it in search api 
- add filter to the UI

for OCR at least

i'm not sure we have a good way yet to track which window is focused, to experiment

**Comment by EzraEllette** [comment]
How should active window be defined? 

Also, I use a lot of different windows so it may be useful to select windows that were active during the time period as well.

**Comment by Csaba8472** [comment]
I'd use this to determine which window is active: https://github.com/sindresorhus/get-windows

In my opinion, if you only query active window's context you won't lose much, because most probably at some point you will make all window you use active so screenpipe can get data from them. On the other hand, right now, I have 28 open windows so I can't search or process with AI anything because it's just too much data.

**Comment by Csaba8472** [comment]
/attempt #683

based on my comment above I'd get the active window, save to db and retrieve through API/UI
