### ISSUE TITLE
[bounty] automating official brew update 

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#692]
/bounty 80

basically update https://github.com/mediar-ai/screenpipe/blob/main/.github/workflows/release-cli.yml to properly automate official brew too when ran 

(if linux is too hard just skip for now, focus on macos)

@Anshgrover23 want to give a shot?

**Comment by Neptune650** [comment]
@louis030195 I can do this - but I need to know what permissions the PAT token in the GitHub CI has.

**Comment by krushnarout** [comment]
> @krushnarout can you re open a PR to actually make this work?
> 
> this does not work https://github.com/mediar-ai/screenpipe/actions/runs/11958669798

Sure, I'll reopen it.

**Comment by krushnarout** [comment]
@louis030195 I found the solution after opening a discussion https://github.com/orgs/Homebrew/discussions/5753. They explained that the duplicate PR happened because someone else also created a PR, so there's not much you can do about that.

They mentioned that the code is correct, but you should remove the entire brew setup. GitHub Actions runners already have Homebrew installed, so there's no need to manually specify the URL or SHA checksum.

https://github.com/orgs/Homebrew/discussions/5753#discussioncomment-11346494

Should I open a new pull request?

**Comment by louis030195** [comment]
> @louis030195 I found the solution after opening a discussion https://github.com/orgs/Homebrew/discussions/5753. They explained that the duplicate PR https://github.com/mediar-ai/screenpipe/actions/runs/11958669798 happened because someone else also created a PR, so there's not much you can do about that.
> 
> They mentioned that the code is correct, but you should remove the entire brew setup. GitHub Actions runners already have Homebrew installed, so there's no need to manually specify the URL or SHA checksum.
> 
> https://github.com/orgs/Homebrew/discussions/5753#discussioncomment-11346494
> 
> Should I open a new pull request?

sure

**Comment by louis030195** [comment]
@krushnarout fyi fixed it https://github.com/mediar-ai/screenpipe/commit/02e3e9fc7de6ca98aacdd5040b1483f5e00de188

**Comment by krushnarout** [comment]
> @krushnarout fyi fixed it [02e3e9f](https://github.com/mediar-ai/screenpipe/commit/02e3e9fc7de6ca98aacdd5040b1483f5e00de188)

Great! Nice to see this working 🚀
