### ISSUE TITLE
[MacOS] System/Output Audio does not work since macos > 15.0

### ISSUE THREAD

**Issue by DmacMcgreg** [mediar-ai/screenpipe#70]
## Steps to Reproduce:
1. brew tap louis030195/screen-pipe https://github.com/louis030195/screen-pipe.git
2. brew install screenpipe
3. screenpipe 

Seems to only be recording audio from my mac or airpods, but not system audio.

**Comment by louis030195** [comment]
thanks for reporting

yes it's a known issue caused by latest macos release (15.0) 

we're will be working on a fix soon

workaround for you is not to wear airpods in a meeting for example so the output will be "heard" by the input (mac mic)

other work around is to install 1.38 or 1.39 i believe should work if you are not on macos 15.0 (14.5 for example should work)

should work fine on windows & linux

**Comment by DmacMcgreg** [comment]
I am on Mac 14.4.1 by the way, so I think perhaps there is another issue?

**Comment by louis030195** [comment]
@DmacMcgreg btw macos audio output works since last week on macos <15.0

there is a $100 bounty to make it work on macos 15.0 https://github.com/mediar-ai/screenpipe/issues/199
