### ISSUE TITLE
[bounty] $150 fix /search

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#754]
definition of done:
- we have unit test that cover all edge cases
- /search works for all edge cases 

i noticed /search broke recently (either related to UI monitoring or speaker identification features), how to reproduce:
- search with both app name and content type will ignore the content type 

for example 

curl ... app_name=cursor&content_type=audio 

will ignore the content type

PS: i thought our tests covered all cases, or something changed, used to cover all and pass

/bounty 150

**Comment by Neptune650** [comment]
> definition of done:
> 
>     * we have unit test that cover all edge cases
> 
>     * /search works for all edge cases
> 
> 
> i noticed /search broke recently (either related to UI monitoring or speaker identification features), how to reproduce:
> 
>     * search with both app name and content type will ignore the content type
> 
> 
> for example
> 
> curl ... app_name=cursor&content_type=audio
> 
> will ignore the content type
> 
> PS: i thought our tests covered all cases, or something changed, used to cover all and pass
> 
> /bounty 150

@louis030195 This indeed seems to have been caused by the UI monitoring changes

I believe the culprit change is here https://github.com/mediar-ai/screenpipe/commit/72bd255a7c9c1baeefea534504133d09ec125a0a#diff-170633f2f9d0398cef747212489ed3dca4efe0d0f20e0813141252ecc25548ceR502-R506

Will send a patch soon
