### ISSUE TITLE
[bug] mkl does not work

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#759]
<img width="1512" alt="Screenshot 2024-11-25 at 11 40 44 AM" src="https://github.com/user-attachments/assets/8c62a2ca-8a20-42c8-a125-cc3bc5d5135b">

@Neptune650 it was more than this

**Comment by Neptune650** [comment]
Will look into this

**Comment by louis030195** [comment]
https://github.com/mediar-ai/screenpipe/actions/runs/12035352415/job/33554103457 @Neptune650

**Comment by Neptune650** [comment]
@louis030195 That's not quite why, because intel-mkl-src downloads it and statically links it for us. What we're missing is adding the additional lib that it needs called libiomp5md.dll, which is included in MKL, but that the crate intel-mkl-src links dynamically by default.

So what would be needed is to install MKL in the runner and copy the necessary lib as an artifact to Tauri.

**Comment by louis030195** [comment]
also I will likely want to switch to another self-hosted runner in the upcoming days because I bought a new windows computer which has nvidia card too (rtx 4060) and better CPU than the Azure VM i think

ideally it's easy to switch

**Comment by Neptune650** [comment]
> also I will likely want to switch to another self-hosted runner in the upcoming days because I bought a new windows computer which has nvidia card too (rtx 4060) and better CPU than the Azure VM i think
> 
> ideally it's easy to switch

@louis030195 Alright, create an issue for it and send me RDP details over Telegram so we can set it up.
