### ISSUE TITLE
Ability to select "all" audio devices

### ISSUE THREAD

**Issue by moltar** [mediar-ai/screenpipe#90]
Today after using screenpipe all day, I realized it was capturing my mic only, but not the other side of the conversation (e.g. a Zoom call).

I realized there's an option (`--audio-device`) to add more audio devices, and even a way to specify multiple.

The problem is that my audio devices can change all the time, and it's not stable.

It would be good to have some option like `--all-audio-devices` that captures feed from all and deduplicates it.

My setup:

- I can use _no_ headphones, just MacBook mic.
- I can use AirPods for calls
- I can use Bose QC34 for deep work

In each scenario, I can also use a Krisp virtual audio filter.

I thought about adding a shell script with all of the params, but the CLI fails if I specify non-existing audio device (e.g. when headphones are not connected).

So, now I have to remember to restart the CLI any time the audio device changes.

**Comment by louis030195** [comment]
yes, atm we "lost" support for system audio due to being broken on MacOS new release 15.0 https://github.com/louis030195/screen-pipe/issues/70

so the work around currently is either:
- do not use headphones (audio output would enter your mac mic)
- find a hack with https://github.com/ExistentialAudio/BlackHole which somehow make system audio captured by screenpipe (would love someone to try this)

long term
- need to make this PR work https://github.com/RustAudio/cpal/pull/894/files
- or integrate blackhole somehow
- do some low level audio stuff 
- also i think we should switch to default device when it changes (say you turn on airpods for a meeting it should switch)

so what you think of would be either to capture all available ones, and do some data processing magic

or always capture default input and output device (switching automatically)?
