### ISSUE TITLE
[bounty] $100 to debug the status button not being clickable on windows (sometimes)

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#903]
basically status button sometimes is not clickable

there was some PR supposedly fixing it https://github.com/mediar-ai/screenpipe/pull/782 but been removed, i don't think it fixed the issue 

this seems to happen only on windows (or i don't remember last time i had this on mac)

related annoying things:
- console being spammed of red when API is not running 
- status check triggering bunch of unnecessary react state update 

/bounty 100

**Comment by kumarvivek1752** [comment]
This only happens when the status is yellow because the backend is not running, while the frontend is running and making too many backend health check API calls. That is why the button is not clickable.

**Comment by kumarvivek1752** [comment]
if `health == null` then  our program enters the following if condition:
```
  if (!health) {
    return (
      <Badge
        variant="outline"
        className="cursor-pointer bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground"
      >
        <Activity className="mr-2 h-4 w-4" />
        status{" "}
        <span className="ml-1 w-2 h-2 rounded-full bg-yellow-500 inline-block animate-pulse" />
      </Badge>
    );
  }
```

This is why, when the status color is yellow, no dialog is opening because we did not implement a dialog for the yellow status.

I can create a dialog to notify the user that the backend is starting or not running, similar to the design shown in the image below:

![image](https://github.com/user-attachments/assets/aa8a27bc-8931-4daf-8938-7deab995e54e)


or I can use the same dialogue but without some variables like: `health.frame_status`, `health.last_frame_timestamp`.etc
because `health == null` :
![image](https://github.com/user-attachments/assets/2ee210f3-eb21-4e3b-8c87-d72eaaf92c6a)



UI looks something like this 
![image](https://github.com/user-attachments/assets/6d434e28-f7cc-4ec8-b1db-fadede17d30a)

**Comment by kumarvivek1752** [comment]
@tribhuwan-kumar basically you did what I discussed in chat

**Comment by KodeSage** [comment]
> @tribhuwan-kumar basically you did what I discussed in chat


very fast moves 😂😂

**Comment by kumarvivek1752** [comment]
> > @tribhuwan-kumar basically you did what I discussed in chat
> 
> very fast moves 😂😂, I would have done same thing sef.

it's 9000 IQ move
